name: Build and Deploy packages

on:
  push:
    branches:
      - main
    
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up .Net Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Create the package
      run: dotnet pack --configuration Release

    - name: Publish
      # run: dotnet nuget push "MoneyExtension/bin/Release/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
      run: dotnet nuget push "MoneyExtension/bin/Release/*.nupkg" -k oy2o2axtsmvxdft72paafkhfs75qkw6e7ezv4brweladqq -s https://api.nuget.org/v3/index.json